### ISSUE TITLE
Heartbeat not updated

### ISSUE THREAD

**Issue by PaulvS** [arendst/Sonoff-MQTT-OTA#4]
Hi Theo,

while browsing trough the sourcecode I see that a heartbeat is implemented. I would expect to see a mqtt message every second at stat/sonoff/heartbeat. However, I don't see this message and when issueing a cmnd/sonoff/status 1 message, the value for the heartbeat is always 0. Any clue why the heartbeat is not updating?

**Comment by arendst** [comment]
Partly correct. Heartbeat is send every hour, not second. My goal was to have some kind of information about auto-reboot of sonoff caused by memory leaks or unable to access the network. Every second would be to much for MQTT I think. LWT is still implemented too.

**Comment by PaulvS** [comment]
I see. I changed the code a bit on my computer to send a heartbeat every minute. In that way I can keep track of the uptime of the units. They seem to be very reliable.
