### ISSUE TITLE
Proplems after flashing

### ISSUE THREAD

**Issue by tom71** [arendst/Sonoff-MQTT-OTA#5]
Hello,

I compiled the code and flashed my device:

`../../tools/esptool/esptool.py --port /dev/ttyUSB0 write_flash -fs 8m 0x00000 ../../esp-sdk/bin/boot_v1.4(b1).bin 0x01000 .firmwares/user1.bin 0xFC000 ../../esp-sdk/bin/esp_init_data_default.bin 0xFE000 ../../esp-sdk/bin/blank.bin
Connecting...
Erasing flash...
Wrote 3072 bytes at 0x00000000 in 0.3 seconds (73.9 kbit/s)...
Erasing flash...
Wrote 309248 bytes at 0x00001000 in 33.4 seconds (74.1 kbit/s)...
Erasing flash...
Wrote 1024 bytes at 0x000fc000 in 0.1 seconds (76.5 kbit/s)...
Erasing flash...
Wrote 4096 bytes at 0x000fe000 in 0.4 seconds (76.8 kbit/s)...

`

After restart I got on the serial console:

`Project sonoff (Topic sonoff, Fallback DVES_832B0D, GroupTopic sonoffs) Version 0.5.6 (Boot 4, SDK 1.4.0)
mode : sta(5c:cf:7f:83:2b:0d)
add if0
f r-1, 
01:54: scandone
no indebuurt3 found, reconnect after 1s
reconnect
f 0, 
01:56: scandone
no indebuurt3 found, reconnect after 1s
reconnect
f -180, 
01:59: scandone
no indebuurt3 found, reconnect after 1s
SC version: V2.5.1
f r-1, 
02:01: scandone
f r-1, 
02:03: scandone
please start sntp first !
`

Did I have the right firmware on the device? Or what else can be wrong?

Thank you for your advice.

Thomas

**Comment by tom71** [comment]
I found, that my user_config was unused. On serial console I can work with all commands.

**Comment by arendst** [comment]
I guess you already solved your problem as indeed the user_config.h file should contain your ssid and password to connect to your wifi.
